### ISSUE TITLE
struct error

### ISSUE THREAD

**Issue by vixvvv** [Kry9toN/KryPtoN-Music-Bot#2]
2021-04-13T20:15:09.354971+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/pyrogram/storage/memory_storage.py", line 38, in open
2021-04-13T20:15:09.354971+00:00 app[worker.1]:     dc_id, test_mode, auth_key, user_id, is_bot = struct.unpack(
2021-04-13T20:15:09.354971+00:00 app[worker.1]: struct.error: unpack requires a buffer of 263 bytes
2021-04-13T20:15:09.354978+00:00 app[worker.1]: [INFO] Bot is running...
2021-04-13T20:15:09.354978+00:00 app[worker.1]: 

how to fix

**Comment by Kry9toN** [comment]
Can you give me more information?

**Comment by vixvvv** [comment]
2021-04-13T21:09:16.780948+00:00 app[worker.1]: Traceback (most recent call last):
2021-04-13T21:09:16.780959+00:00 app[worker.1]:   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
2021-04-13T21:09:16.780960+00:00 app[worker.1]:     return _run_code(code, main_globals, None,
2021-04-13T21:09:16.780960+00:00 app[worker.1]:   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
2021-04-13T21:09:16.780961+00:00 app[worker.1]:     exec(code, run_globals)
2021-04-13T21:09:16.780961+00:00 app[worker.1]:   File "/app/krypton/__main__.py", line 340, in <module>
2021-04-13T21:09:16.780962+00:00 app[worker.1]:     app.run()
2021-04-13T21:09:16.780962+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/utilities/run.py", line 61, in run
2021-04-13T21:09:16.780962+00:00 app[worker.1]:     self.start()
2021-04-13T21:09:16.780963+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/pyrogram/sync.py", line 56, in async_to_sync_wrap
2021-04-13T21:09:16.780963+00:00 app[worker.1]:     return loop.run_until_complete(coroutine)
2021-04-13T21:09:16.780964+00:00 app[worker.1]:   File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
2021-04-13T21:09:16.780964+00:00 app[worker.1]:     return future.result()
2021-04-13T21:09:16.780964+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/utilities/start.py", line 53, in start
2021-04-13T21:09:16.780965+00:00 app[worker.1]:     is_authorized = await self.connect()
2021-04-13T21:09:16.780965+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/auth/connect.py", line 39, in connect
2021-04-13T21:09:16.780965+00:00 app[worker.1]:     await self.load_session()
2021-04-13T21:09:16.780966+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/pyrogram/client.py", line 669, in load_session
2021-04-13T21:09:16.780966+00:00 app[worker.1]:     await self.storage.open()
2021-04-13T21:09:16.780966+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/pyrogram/storage/memory_storage.py", line 38, in open
2021-04-13T21:09:16.780967+00:00 app[worker.1]:     dc_id, test_mode, auth_key, user_id, is_bot = struct.unpack(
2021-04-13T21:09:16.780967+00:00 app[worker.1]: struct.error: unpack requires a buffer of 263 bytes
2021-04-13T21:09:16.781081+00:00 app[worker.1]: [INFO] Bot is running...
2021-04-13T21:09:16.781082+00:00 app[worker.1]:

**Comment by vixvvv** [comment]
I skipped install ffmpeg, can you give tutroial?

**Comment by Kry9toN** [comment]
> I skipped install ffmpeg, can you give tutroial?

You deploy from link on my Readme?

**Comment by vixvvv** [comment]
yep, on heroku

**Comment by Kry9toN** [comment]
Try redeploy again, i run on my heroku it fine

**Comment by vixvvv** [comment]
struct.error: unpack requires a buffer of 263 bytes.

still same. is this problem in ffmpeg or what?

**Comment by Kry9toN** [comment]
If you deploy from link/image deploy on my description, that no ffmpeg issue
